name: test

on: [push, pull_request]

# Stop previous jobs if a new one starts
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.7, 3.0, 3.1, 3.2, 3.3, head, jruby ]
        os: [ ubuntu-latest, flyci-macos-large-latest-m2 ]

    name: >-
      ${{matrix.os}}-ruby-${{matrix.ruby}}
    runs-on: ${{matrix.os}}
    continue-on-error: ${{matrix.ruby == 'head'}}

    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Set up ruby and bundle
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true

      - name: Run test
        run: bundle exec rake test
